# Generated by Django 5.1.3 on 2024-11-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='current_price',
        ),
        migrations.AlterField(
            model_name='client',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=13),
        ),
    ]
